"use client";

import type { Consultation } from "@/lib/patientTypes";
import { fmtDateTime } from "@/lib/format";
import { Badge, EmptyState } from "../ui";
import VoiceSignalBadge from "./VoiceSignalBadge";

function Item({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="min-w-0">
      <p className="eyebrow">{label}</p>
      <div className="mt-1 text-sm">{children}</div>
    </div>
  );
}

const followUpText = (f: Consultation["follow_up"]): string | null => {
  if (!f) return null;
  const note = f["note"];
  return typeof note === "string" && note ? note : [f["type"], f["date"], f["status"]].filter((x) => typeof x === "string" && x).join(" ") || null;
};

/** Derived from completed Voxera calls, their summaries and assessments. AI-generated, not clinician notes. */
export default function ConsultationHistory({ items }: { items: Consultation[] }) {
  if (items.length === 0) {
    return <div className="card"><EmptyState icon="☎" title="No previous consultations" hint="Voxera consultations and their summaries appear here." /></div>;
  }
  return (
    <div className="space-y-3">
      <p className="text-muted text-xs">Summaries are generated by Voxera from the call. They are not clinician-authored notes.</p>
      {items.map((c) => (
        <article key={c.id} className={`card triage ${c.emergency ? "triage-critical" : "triage-info"} p-4`}>
          <div className="flex flex-wrap items-center gap-2">
            <span className="font-bold">{fmtDateTime(c.date)}</span>
            {c.emergency && <Badge tone="critical">Emergency</Badge>}
            {c.risk_level && <Badge>{c.risk_level}</Badge>}
            <span className="ml-auto"><VoiceSignalBadge signal={c.voice_signal} /></span>
          </div>
          <div className="mt-3 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            <Item label="Chief complaint">{c.chief_complaint ?? "—"}</Item>
            <Item label="Assessment">{c.assessment ?? "—"}</Item>
            <Item label="Guidance given">{c.guidance.length ? c.guidance.join(", ") : "—"}</Item>
            {c.otc_guidance.length > 0 && (
              <Item label="Voxera OTC guidance (not a prescription)">{c.otc_guidance.join(", ")}</Item>
            )}
            <Item label="Referral">{c.outcome?.includes("emergency") ? "Escalated" : "—"}</Item>
            <Item label="Follow-up">{followUpText(c.follow_up) ?? "—"}</Item>
          </div>
          {c.clinical_context?.conclusion && (
            <p className="text-muted mt-3 text-xs">Triage conclusion: {c.clinical_context.conclusion.replaceAll("_", " ").toLowerCase()}</p>
          )}
        </article>
      ))}
    </div>
  );
}
